### ISSUE TITLE
Question: Does this work with Thycotic secret server if tenant is using SSO?

### ISSUE THREAD

**Issue by dbloch3643** [DelineaXPM/SS-ADO-BuildTask#15]
Our company uses SSO with Thycotic, will this widget work?  If not, how would I go about pulling secrets within ADO pipelines with Thycotic that uses SSO?

**Comment by dbloch3643** [comment]
After some testing I was able to get it to work with our tenant that uses SSO

**Comment by tylerezimmerman** [comment]
@dbloch3643 Apologies about the delayed response. Feel free to add a section to our ReadMe to help users in the future!
