### ISSUE TITLE
0.0.7 error

### ISSUE THREAD

**Issue by cspiess24** [DelineaXPM/SS-ADO-BuildTask#39]
With the recent upgrade to 0.0.7 I am now seeing the following error during the pipeline run. 

##[error]File not found: '/home/user/agent/_work_/_tasks/DelineaSS_<redcated_guid>/0.0.7/index.js'

**Comment by tylerezimmerman** [comment]
@cspiess24 thank you for pointing this out, we are investigating.

**Comment by tylerezimmerman** [comment]
@cspiess24 we just released version 0.0.8, can you please confirm if this issue has been resolved for you?

**Comment by cspiess24** [comment]
@tylerezimmerman I just tested and it is working as expected now. Thanks for the quick turnaround!
